Add flake8 linting.
PrivateStorageio/ZKAPAuthorizer pull request #243
Opened 2021-11-02 17:56 UTC by tomprince

Issues reported
- E302 expected 2 blank lines, found 1
- E402 module level import not at top of file
- E501 line too long 
- E722 do not use bare 'except'

2021-11-03 16:19 UTC, exarkun requested changes
Thanks.  I think I looked at all the changes distinct to this branch.  Some comments inline.  In particular, I'm not convinced the `except` to `except Exception` change is safe/correct.  Handling `BaseException` in all those places would at least be the _same_ as it was before (whether it was 100% correct before or not could be a separate question of course).

2021-11-03 16:19 UTC, exarkun commented on src/_zkapauthorizer/schema.py
> -            [created] text,                     -- An ISO8601 date+time string.
Hm.  These text changes are all semantically null so they should be fine.  However, SQLite3 stores the schema as text in the database and as a result I'm vaguely afraid of changing the exact text of the old versions of the schema.

So I read https://sqlite.org/fileformat2.html#ffschema and I'm less afraid now.  The text is stored but of course SQLite3 has to parse it to actually do anything with it so non-semantic changes should make no difference to operation.  Further, SQLite3 already performs certain normalization to the text before storing it.  At first I thought it collapsed all whitespace in the statement down to a single space but on experimentation I see that it really only does this for whitespace between "create table" and the table name - not any subsequent whitespace.  Still, it seems the difference in the text should be harmless.

The moved comments are slightly different but it seems like they should likewise be harmless.

So, okay, no adjustment required here.

2021-11-04 18:08 UTC, tomprince commented on .flake8
> +extend-ignore = E203
No. This is the suggested black-compatible configuration (per https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8). I've added a comment.

2021-11-04 18:25 UTC, tomprince commented on src/_zkapauthorizer/tests/_exception.py
> +        except Exception:
It looks like this matcher is available in testtools now, so I've removed this module and adjusted the imports.

2021-11-04 18:39 UTC, exarkun commented on src/_zkapauthorizer/tests/_exception.py
> +        except Exception:
I have a vague memory of the one in testtools doing worse error reporting.

2021-11-08 21:15 UTC, tomprince commented
I'm going to close this for the moment. Getting black and isort landed was the part that was more significant to me. I'm not sure the changes here are worth the effort, and I don't seem to have the right kind of attention to detail make the changes here at the moment. I will split out the changes to remove the need for `registerAdapter`, since I believe that part doesn't have any issues.

2021-11-08 21:15 UTC, closed without merging